import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  FaFacebookF,
  FaLinkedinIn,
  FaTwitter,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import { GrLocation, GrMailOption } from "react-icons/gr";
import { PiPhoneCallLight } from "react-icons/pi";
import Image from "next/image";
import { MdOutlineKeyboardArrowDown } from "react-icons/md";
import { TbCategoryPlus } from "react-icons/tb";
import {
  Button,
  ColorSchemeScript,
  Indicator,
  MantineProvider,
} from "@mantine/core";
import NotificationIcon from "@/components/home/notification-icon";
import LoveIcon from "@/components/home/love-icon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <main className=" flex flex-col flex-1 h-screen">
            <header className=" flex flex-col">
              <nav className=" py-[11px] px-[clamp(3.1rem,8.375vw,7.4rem)] flex justify-between bg-purple text-white">
                <section className=" flex gap-[clamp(0.9rem,2vw,1.8rem)] ">
                  <div className=" flex  gap-[10px] items-center ">
                    <GrLocation color="#DAD4FF" size={20} />

                    <p className=" text-creame text-[14px] font-medium font-[Inter]">
                      123 Str., Lagos, Nigeria
                    </p>
                  </div>

                  <div className=" flex items-center gap-[9.6px]">
                    <GrMailOption color="#DAD4FF" />
                    <p className=" text-creame text-[14px] font-medium font-[Inter]">
                      info@pathfinders.com
                    </p>
                  </div>
                </section>
                <section className="flex gap-[1.18rem]">
                  <div className=" flex items-center gap-[9.6px]">
                    <PiPhoneCallLight color="#DAD4FF" size={20} />
                    <p className=" text-creame text-[14px] font-medium font-[Inter]">
                      Call us:
                    </p>
                    <p className=" text-creame text-[14px] font-medium font-[Inter]">
                      234 801234567
                    </p>
                  </div>

                  <div className=" flex gap-[9.6px] items-center">
                    <p className=" text-[#DAD4FF] text-[14px] font-medium">
                      Follow Us On :
                    </p>
                    <article className=" flex gap-[9.6px]">
                      <FaFacebookF color="#E7EFFC" size={16} />
                      <FaTwitter color="#E7EFFC" size={16} />
                      <FaWhatsapp color="#E7EFFC" size={18} />
                      <FaLinkedinIn color="#E7EFFC" size={16} />
                      <FaYoutube color="#E7EFFC" size={16} />
                    </article>
                  </div>
                </section>
              </nav>

              <div className="py-[11px] px-[clamp(3.1rem,8.375vw,7.4rem)] justify-between items-center flex">
                <section className=" flex gap-[clamp(2.5rem,5.9vw,5.3rem)] items-center">
                  <figure className=" w-[clamp(2.7rem,4.4vw,4.4rem)] h-[clamp(2.7rem,4.4vw,4.4rem)]">
                    <Image
                      className="!h-full !w-full"
                      src="/logo.svg"
                      width={100}
                      height={0}
                      alt="logo"
                    />
                  </figure>

                  <ul className=" flex justify-between gap-[11px]">
                    <li>Home</li>
                    <li>Resources</li>
                    <li>Mentors</li>
                    <li>Blog</li>
                  </ul>
                </section>
                <section className=" flex gap-6 items-center ">
                  <div className="flex border-[#8D9DB5] h-12 px-[9px] border items-center rounded-[50px] min-w-[120px] w-[80%] overflow-hidden">
                    <article className=" flex gap-[10px] items-center">
                      <TbCategoryPlus color="#7630F7" />
                      <p className=" text-black text-[14px] font-medium">
                        Categories
                      </p>
                      <MdOutlineKeyboardArrowDown />
                    </article>
                    <input
                      type="text"
                      placeholder="Search For Mentors . . ."
                      className="border-none outline-none placeholder:text-[14px] placeholder:text-[#8D9DB5] placeholder:font-normal border-l"
                    />
                  </div>

                  <div className=" flex gap-[29px]">
                    <article className=" flex gap-[29px]">
                      <div className=" gap-[14px] flex ">
                        <Indicator
                          inline
                          label="0"
                          size={18}
                          color="#4B0082"
                          offset={6}
                        >
                          <span>
                            <LoveIcon />
                          </span>
                        </Indicator>
                        <Indicator
                          inline
                          label="0"
                          size={18}
                          color="#4B0082"
                          offset={6}
                        >
                          <span>
                            <NotificationIcon />
                          </span>
                        </Indicator>
                      </div>
                    </article>

                    <Button className=" bg-purple rounded-[50px] hover:bg-[#7630F7] whitespace-nowrap text-white ">
                      Log in
                    </Button>
                  </div>
                </section>
              </div>
            </header>

            <div className=" flex flex-1">{children}</div>

            <footer className="  bg-purple  py-[37px]">
              <section className=" mx-auto flex justify-between max-w-[1400px]">
                <div className=" flex flex-col gap-[13px]">
                  <figure className=" w-[clamp(2.7rem,4.4vw,4.4rem)] h-[clamp(2.7rem,4.4vw,4.4rem)]">
                    <Image
                      className="!h-full !w-full"
                      src="/logo.svg"
                      width={100}
                      height={0}
                      alt="logo"
                    />
                  </figure>
                  <article>
                    <p className=" text-[14px] text-[#B2BBCC] font-medium">
                      123 Street, Lagos, Nigeria
                    </p>
                    <p className=" text-[14px] text-[#B2BBCC] font-medium">
                      +234 801234567
                    </p>
                  </article>
                </div>
                <div className=" flex flex-col gap-[20px]">
                  <article className=" flex gap-[16px] flex-col">
                    <h2 className=" text-[20px] font-semibold text-white">
                      Useful Links
                    </h2>
                    <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                  </article>
                  <ul className=" flex flex-col gap-[10px] ">
                    <li className=" text-[#B2BBCC] font-medium text-[14px]">
                      {" "}
                      Our values
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      {" "}
                      Our advisory board
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Our partners
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Become a partner
                    </li>
                  </ul>
                </div>
                <div className=" flex flex-col gap-[20px]">
                  <article className=" flex gap-[16px] flex-col">
                    <h2 className=" text-[20px] font-semibold text-white">
                      Our Company
                    </h2>
                    <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                  </article>
                  <ul className=" flex flex-col gap-[10px] ">
                    <li className=" text-[#B2BBCC] font-medium text-[14px]">
                      Contact Us
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Become Teacher
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Blog
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Instructor
                    </li>
                    <li className="text-[#B2BBCC] font-medium text-[14px]">
                      Events
                    </li>
                  </ul>
                </div>
                <div className=" flex flex-col gap-[20px]">
                  <article className=" flex gap-[16px] flex-col">
                    <h2 className=" text-[20px] font-semibold text-white">
                      Get In Touch
                    </h2>
                    <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                  </article>
                  <section className=" flex flex-col gap-[40px]">
                    <article className=" flex flex-col gap-[18p]">
                      <p className=" text-[#B2BBCC] font-medium text-[14px] w-[229px]">
                        We would like to connect with you, follow us on
                      </p>
                    </article>
                    <article className=" flex gap-[9.6px]">
                      <FaFacebookF color="#E7EFFC" size={16} />
                      <FaTwitter color="#E7EFFC" size={16} />
                      <FaWhatsapp color="#E7EFFC" size={18} />
                      <FaLinkedinIn color="#E7EFFC" size={16} />
                      <FaYoutube color="#E7EFFC" size={16} />
                    </article>
                  </section>
                </div>
              </section>
            </footer>
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
